version: '3.9'

services:
  app:
    container_name: app
    build: ./Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - '5173:5173'
      - '24678:24678'
    tty: true
    command: sh -c "npm install && npm run dev"
